### ISSUE TITLE
Compile error with last appdaemon

### ISSUE THREAD

**Issue by sagitt** [Petro31/ad_group_all#7]
With last updates, this addon won't work

**Comment by sagitt** [comment]
<img width="614" alt="Screenshot 2023-04-11 alle 22 59 19" src="https://user-images.githubusercontent.com/169086/231286920-1ab3e0fb-0584-4f28-bae7-cf93a5274d4b.png">

**Comment by PolestarWx** [comment]
A module is missing

```
2023-04-13 13:49:34.682639 WARNING alarm: ------------------------------------------------------------
2023-04-13 13:50:10.358851 WARNING Error: ------------------------------------------------------------
2023-04-13 13:50:10.359015 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/ad_group_all/group_all.py:
2023-04-13 13:50:10.359139 WARNING Error: ------------------------------------------------------------
2023-04-13 13:50:10.360393 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 999, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 782, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/appdaemon/apps/ad_group_all/group_all.py", line 2, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'
```

**Comment by sagitt** [comment]
i hope in a fix.

**Comment by Petro31** [comment]
Sorry for the late reply.  I half forgot about these repos.  Anyways, apparently voluptuous was removed as a dependency to the addon.  So now you need to manually add it in the addon via the ui.  That will fix the issue.
